# REF ---------------------------------------------------------------------
# Pan-human Azimuth (AzimuthAPI) — intro vignette as a runnable script
# Source: https://satijalab.org/pan_human_azimuth/r/articles/intro_azimuthapi_vignette

# This vignette demonstrates how to install and use AzimuthAPI, an interface for cell type annotation using the Pan-human Azimuth neural network.
# The API takes a Seurat object and returns hierarchical cell type predictions, confidence scores, and low-dimensional embeddings useful for visualization.

# This is the test to run the tool locally. before preceeding make sure to:
# - create the conda env (I decided to create a local project folder, but it can be also a general conda env). The yaml is located in: "../env//env_panhumanpy.yml"
# - download the model weights ('https://zenodo.org/records/20401417/files/panhumanpy_inference_model_v1.keras?download=1') and link them into the expected cache folder (~/.cache/panhumanpy/v1/inference_model/inference_model.keras)
# - activate the python env inside the R script (Sys.setenv(RETICULATE_PYTHON = "./.conda-pan-human-azimuth/bin/python"))

# libraries ---------------------------------------------------------------
library(AzimuthAPI)
library(Seurat)
library(SeuratData)
library(reticulate)
library(tidyverse)
library(presto)

# 2. Point reticulate at the local panhumanpy Python environment -------------
# Pin RETICULATE_PYTHON directly to the env's interpreter (must be set before reticulate initializes any Python session).
# This is more robust than use_condaenv(name) on this machine, since that relies on `conda env list` to discover environments, which does not reliably see micromamba envs.
# Adjust the path if your pan-human-azimuth env lives elsewhere (check with: micromamba env list).
Sys.setenv(RETICULATE_PYTHON = "./.conda-pan-human-azimuth/bin/python")

# Confirm reticulate actually loaded THIS interpreter and that it can see panhumanpy inside it. 
py_config()
# might expose token
# Sys.getenv()
Sys.getenv(c("RETICULATE_PYTHON", "CONDA_PREFIX", "CONDA_DEFAULT_ENV"))

cat("Active Python:", py_config()$python, "\n")
cat("panhumanpy version:", as.character(import("panhumanpy")$`__version__`), "\n")

# read in the data --------------------------------------------------------
# list all the reference available
AvailableData()

# For this vignette, we will demonstrate annotating a dataset of human bone marrow mononuclear (BMNC) cells that we published as part of Stuart, Butler et al Cell 2019. (https://doi.org/10.1016/j.cell.2019.05.031)
# This dataset is available through `SeuratData`.
# InstallData("bmcite")

# Load the data from `SeuratData`. Here we also make sure to normalize the data before running Pan-human Azimuth.
bmcite <- LoadData("bmcite")

# perform standard log-normalization with the NormalizeData function prior to annotating.
# Variable gene selection is not required; users should keep all quantified genes in the object prior to annotation.
bmcite <- NormalizeData(bmcite)

# explore the dataset
bmcite
bmcite@meta.data %>% head()

# ---- Annotate a dataset with Pan-human Azimuth ------------------------------
# Users have two options for running Pan-human Azimuth on their dataset: cloud-based or local.
# The cloud-based option is the easiest to use, and requires no additional setup.
# The local option requires setting up a Python environment with panhumanpy (Python package for the Pan-human Azimuth neural network) and its dependencies.
# Annotation results, regardless of the method used, are stored in the Seurat object as cell-level metadata, and the embeddings generated by the underlying neural network are stored in a new Seurat reduction.

# Option 2: run `ANNotate` (requires panhumanpy in a Python env reticulate can see)
# run the minimal outpur that should replicate the cloud/remote version of the analysis
t_init_minimal <- Sys.time()
bmcite_annMinimal <- ANNotate(bmcite, output_mode = "minimal")
t_end_minimal <- Sys.time()
# time
t_end_minimal - t_init_minimal

saveRDS(bmcite_annMinimal, "../out/object/bmcite_ann_localMinimal.rds")

# output_mode = 'detailed' additionally returns the raw per-level labels (level_1_labels ... level_N_labels), used in 02_hierarchy_consistency_check.R to inspect exactly where a cell's hierarchy becomes inconsistent. First run downloads and caches the model weights locally - can take a while.
t_init_detailed <- Sys.time()
bmcite_annDetailed <- ANNotate(bmcite, output_mode = "detailed")
t_end_detailed <- Sys.time()
# time
t_end_detailed - t_init_detailed

saveRDS(bmcite_annDetailed, "../out/object/bmcite_ann_localDetailed.rds")



# explore the object after the annotation
bmcite_annMinimal
bmcite_annDetailed
bmcite_annMinimal@meta.data %>% head()
bmcite_annDetailed@meta.data %>% head()

bmcite_annDetailed@meta.data %>% 
  filter(full_consistent_hierarchy == F)

bmcite_ann@reductions
